<html>
  <head>
    <meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Python基础10-异常 | NoteForStudy</title>
<link rel="shortcut icon" href="https://y-rui.github.io/favicon.ico?v=1608466007398">
<link href="https://cdn.jsdelivr.net/npm/remixicon@2.3.0/fonts/remixicon.css" rel="stylesheet">
<link rel="stylesheet" href="https://y-rui.github.io/styles/main.css">
<link rel="alternate" type="application/atom+xml" title="Python基础10-异常 | NoteForStudy - Atom Feed" href="https://y-rui.github.io/atom.xml">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700">



    <meta name="description" content="
在程序执行过程中发生的任何错误都是异常。每个异常显示一些相关的错误信息，比如你在 Python3 中使用 Python2 独有的语法就会发生 SyntaxError
不小心在行首多打了一个空格就会产生 IndentationError

..." />
    <meta name="keywords" content="Python,实验楼" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.10.0/katex.min.css">
    <script src="https://cdn.bootcss.com/highlight.js/9.12.0/highlight.min.js"></script>
  </head>
  <body>
    <div class="main">
      <div class="main-content">
        <div class="site-header">
  <a href="https://y-rui.github.io">
  <img class="avatar" src="https://y-rui.github.io/images/avatar.png?v=1608466007398" alt="">
  </a>
  <h1 class="site-title">
    NoteForStudy
  </h1>
  <p class="site-description">
    温故而知新
  </p>
  <div class="menu-container">
    
      
        <a href="/" class="menu">
          首页
        </a>
      
    
      
        <a href="/archives" class="menu">
          归档
        </a>
      
    
      
        <a href="/tags" class="menu">
          标签
        </a>
      
    
      
        <a href="/post/about" class="menu">
          关于
        </a>
      
    
  </div>
  <div class="social-container">
    
      
        <a href="https://github.com/y-rui" target="_blank">
          <i class="ri-github-line"></i>
        </a>
      
    
      
    
      
    
      
    
      
    
  </div>
</div>

        <div class="post-detail">
          <article class="post">
            <h2 class="post-title">
              Python基础10-异常
            </h2>
            <div class="post-info">
              <span>
                2020-08-16
              </span>
              <span>
                5 min read
              </span>
              
                <a href="https://y-rui.github.io/tag/uGwwKRarA/" class="post-tag">
                  # Python
                </a>
              
                <a href="https://y-rui.github.io/tag/ZJvG0o9NN/" class="post-tag">
                  # 实验楼
                </a>
              
            </div>
            
            <div class="post-content-wrapper">
              <div class="post-content">
                <ul>
<li>在程序执行过程中发生的任何错误都是异常。每个异常显示一些相关的错误信息，比如你在 Python3 中使用 Python2 独有的语法就会发生 SyntaxError</li>
<li>不小心在行首多打了一个空格就会产生 IndentationError</li>
</ul>
<h2 id="nameerror">NameError</h2>
<ul>
<li>当访问一个未定义的变量则会发生 NameError</li>
</ul>
<pre><code>&gt;&gt;&gt; print(kushal)
Traceback (most recent call last):
  File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt;
NameError: name 'kushal' is not defined
</code></pre>
<p>最后一行包含了错误的详细信息，其余行显示它是如何发生（或什么引起该异常）的详细信息</p>
<h2 id="typeerror">TypeError</h2>
<ul>
<li>TypeError 也是一种经常出现的异常。当操作或函数应用于不适当类型的对象时引发，一个常见的例子是对整数和字符串做加法</li>
</ul>
<pre><code>&gt;&gt;&gt; print(1 + &quot;kushal&quot;)
Traceback (most recent call last):
  File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt;
TypeError: unsupported operand type(s) for +: 'int' and 'str'
</code></pre>
<h2 id="处理异常">处理异常</h2>
<p>我们使用 try...except 块来处理任意异常。基本的语法像这样</p>
<pre><code>try:
    statements to be inside try clause
    statement2
    statement3
    ...
except ExceptionName:
    statements to evaluated in case of ExceptionName happens
</code></pre>
<p>它以如下方式工作</p>
<ul>
<li>首先，执行  try  子句 （在  try  和  except  关键字之间的部分）</li>
<li>如果没有异常发生，except  子句 在  try  语句执行完毕后就被忽略了</li>
<li>如果在 try 子句执行过程中发生了异常，那么该子句其余的部分就会被忽略。</li>
<li>如果异常匹配于  except  关键字后面指定的异常类型，就执行对应的 except 子句。然后继续执行  try  语句之后的代码</li>
<li>如果发生了一个异常，在  except  子句中没有与之匹配的分支，它就会传递到上一级  try  语句中</li>
<li>如果最终仍找不到对应的处理语句，它就成为一个未处理异常，终止程序运行，显示提示信息</li>
</ul>
<p>下面的例子展示了这些情况</p>
<pre><code>&gt;&gt;&gt; def get_number():
...     &quot;Returns a float number&quot;
...     number = float(input(&quot;Enter a float number: &quot;))
...     return number
...
&gt;&gt;&gt;
&gt;&gt;&gt; while True:
...     try:
...         print(get_number())
...     except ValueError:
...         print(&quot;You entered a wrong value.&quot;)
...
Enter a float number: 45.0
45.0
Enter a float number: 24,0
You entered a wrong value.
Enter a float number: Traceback (most recent call last):
  File &quot;&lt;stdin&gt;&quot;, line 3, in &lt;module&gt;
  File &quot;&lt;stdin&gt;&quot;, line 3, in get_number
KeyboardInterrupt
</code></pre>
<p>首先我输入了一个合适的浮点值，解释器返回输出这个值</p>
<p>然后我输入以逗号分隔的值，抛出 ValueError 异常，except 子句捕获之，并且打印出错误信息</p>
<p>第三次我按下 Ctrl + C ，导致了 KeyboardInterrupt 异常发生，这个异常并未在 except 块中捕获，因此程序执行被中止</p>
<p>一个空的 except 语句能捕获任何异常。阅读下面的代码</p>
<pre><code>&gt;&gt;&gt; try:
...     input() # 输入的时候按下 Ctrl + C 产生 KeyboardInterrupt
... except:
...     print(&quot;Unknown Exception&quot;)
...
Unknown Exception
</code></pre>
<h2 id="抛出异常">抛出异常</h2>
<p>使用 raise 语句抛出一个异常</p>
<pre><code>&gt;&gt;&gt; raise ValueError(&quot;A value error happened.&quot;)
Traceback (most recent call last):
  File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt;
ValueError: A value error happened.
</code></pre>
<p>我们可以捕获任何其它普通异常一样，来捕获这些异常</p>
<pre><code>&gt;&gt;&gt; try:
...     raise ValueError(&quot;A value error happened.&quot;)
... except ValueError:
...     print(&quot;ValueError in our code.&quot;)
...
ValueError in our code.
</code></pre>
<h2 id="定义清理行为">定义清理行为</h2>
<p>try 语句还有另一个可选的 finally 子句，目的在于定义在任何情况下都一定要执行的功能</p>
<pre><code>&gt;&gt;&gt; try:
...     raise KeyboardInterrupt
... finally:
...     print('Goodbye, world!')
...
Goodbye, world!
KeyboardInterrupt
Traceback (most recent call last):
  File &quot;&lt;stdin&gt;&quot;, line 2, in ?
</code></pre>
<p>不管有没有发生异常，finally 子句 在程序离开 try 后都一定会被执行。当 try 语句中发生了未被 except 捕获的异常（或者它发生在 except 或 else 子句中），在 finally 子句执行完后它会被重新抛出</p>
<p>在真实场景的应用程序中，finally 子句用于释放外部资源（文件或网络连接之类的），无论它们的使用过程中是否出错</p>

              </div>
              <div class="toc-container">
                <ul class="markdownIt-TOC">
<li>
<ul>
<li><a href="#nameerror">NameError</a></li>
<li><a href="#typeerror">TypeError</a></li>
<li><a href="#%E5%A4%84%E7%90%86%E5%BC%82%E5%B8%B8">处理异常</a></li>
<li><a href="#%E6%8A%9B%E5%87%BA%E5%BC%82%E5%B8%B8">抛出异常</a></li>
<li><a href="#%E5%AE%9A%E4%B9%89%E6%B8%85%E7%90%86%E8%A1%8C%E4%B8%BA">定义清理行为</a></li>
</ul>
</li>
</ul>

              </div>
            </div>
          </article>
        </div>

        
          <div class="next-post">
            <div class="next">下一篇</div>
            <a href="https://y-rui.github.io/post/python-tiao-zhan-2-zi-fu-chuan-cao-zuo/">
              <h3 class="post-title">
                Python挑战2-字符串操作
              </h3>
            </a>
          </div>
        

        

        <div class="site-footer">
  Powered by <a href="https://github.com/y-rui" target="_blank">y-rui</a>
  <a class="rss" href="https://y-rui.github.io/atom.xml" target="_blank">
    <i class="ri-rss-line"></i> RSS
  </a>
</div>

      </div>
    </div>

    <script>
      hljs.initHighlightingOnLoad()

      let mainNavLinks = document.querySelectorAll(".markdownIt-TOC a");

      // This should probably be throttled.
      // Especially because it triggers during smooth scrolling.
      // https://lodash.com/docs/4.17.10#throttle
      // You could do like...
      // window.addEventListener("scroll", () => {
      //    _.throttle(doThatStuff, 100);
      // });
      // Only not doing it here to keep this Pen dependency-free.

      window.addEventListener("scroll", event => {
        let fromTop = window.scrollY;

        mainNavLinks.forEach((link, index) => {
          let section = document.getElementById(decodeURI(link.hash).substring(1));
          let nextSection = null
          if (mainNavLinks[index + 1]) {
            nextSection = document.getElementById(decodeURI(mainNavLinks[index + 1].hash).substring(1));
          }
          if (section.offsetTop <= fromTop) {
            if (nextSection) {
              if (nextSection.offsetTop > fromTop) {
                link.classList.add("current");
              } else {
                link.classList.remove("current");    
              }
            } else {
              link.classList.add("current");
            }
          } else {
            link.classList.remove("current");
          }
        });
      });

    </script>
  </body>
</html>
